text_data = [
    "The quick brown fox jumped over the lazy dog.",
    "She sells sea shells by the sea shore every morning.",
    "A bird in the hand is worth two in the bush.",
    "It is better to have loved and lost than never to have loved at all.",
    "Actions speak louder than words but words still matter.",
    "Knowledge is power, but wisdom is the application of knowledge.",
    "Time flies when you are having fun with friends.",
    "The early bird catches the worm, but the second mouse gets the cheese.",
    "Patience is a virtue, but impatience can lead to innovation.",
    "All that glitters is not gold, but some things shine bright.",
    "A journey of a thousand miles begins with a single step.",
    "The pen is mightier than the sword, but both have their uses.",
    "When life gives you lemons, make lemonade.",
    "Don't count your chickens before they hatch, but prepare for them.",
    "The grass is always greener on the other side of the fence.",
    "An apple a day keeps the doctor away, but exercise helps too.",
    "Success is not final, failure is not fatal: It’s the courage to continue.",
    "Better late than never, but never late is better.",
    "Honesty is the best policy, but insanity is a better defense.",
    "The best way to predict the future is to create it.",
    "You miss 100% of the shots you don’t take.",
    "Dream big, work hard, stay focused, and make it happen.",
    "If you want to go fast, go alone. If you want to go far, go together.",
    "Two heads are better than one, especially in problem-solving.",
    "Don’t judge a book by its cover, but a title says a lot.",
    "The only thing we have to fear is fear itself.",
    "A fool thinks himself to be wise, but a wise man knows himself to be a fool.",
    "A picture is worth a thousand words, but words can paint a picture.",
    "Every cloud has a silver lining, but sometimes you have to search for it.",
    "Life is what happens when you’re busy making other plans.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "In three words I can sum up everything I've learned about life: it goes on.",
    "Life is really simple, but we insist on making it complicated.",
    "The best revenge is massive success, but kindness always works wonders.",
    "You can't help everyone, but everyone can help someone.",
    "Tough times never last, but tough people do.",
    "Happiness is not something ready-made. It comes from your own actions.",
    "The secret to getting ahead is getting started.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Don't watch the clock; do what it does. Keep going.",
    "It always seems impossible until it’s done.",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    "A person who never made a mistake never tried anything new.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Good things come to those who wait, but better things come to those who hustle.",
    "Start where you are. Use what you have. Do what you can.",
    "Life isn’t about finding yourself. It’s about creating yourself.",
    "You don’t have to be great to start, but you have to start to be great.",
    "It’s not whether you get knocked down, it’s whether you get up.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "If you want to live a happy life, tie it to a goal, not to people or things.",
    "The only way to do great work is to love what you do.",
    "Believe you can and you're halfway there.",
    "Do not wait to strike till the iron is hot, but make it hot by striking.",
    "You must be the change you wish to see in the world.",
    "A friend to all is a friend to none, but loyalty matters most.",
    "The only thing worse than being talked about is not being talked about.",
    "The only impossible journey is the one you never begin.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "You cannot swim for new horizons until you have courage to lose sight of the shore.",
    "Great things are not done by impulse, but by a series of small things brought together.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Never bend your head. Always hold it high. Look the world straight in the eye.",
    "The most common way people give up their power is by thinking they don’t have any.",
    "In the end, we will remember not the words of our enemies, but the silence of our friends.",
    "The greatest wealth is to live content with little.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "The only way to do great work is to love what you do.",
    "In order to succeed, we must first believe that we can.",
    "I attribute my success to this: I never gave or took any excuse.",
    "The way to get started is to quit talking and begin doing.",
    "Don't be afraid to give up the good to go for the great.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    "You only live once, but if you do it right, once is enough.",
    "Failure is the opportunity to begin again, this time more intelligently.",
    "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.",
    "Success is not in what you have, but who you are.",
    "Don’t let yesterday take up too much of today.",
    "Success is liking yourself, liking what you do, and liking how you do it.",
    "The road to success and the road to failure are almost exactly the same.",
    "The difference between ordinary and extraordinary is that little extra.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Do what you can, with what you have, where you are.",
    "If you're going through hell, keep going.",
    "Everything you can imagine is real.",
    "The best dreams happen when you’re awake.",
    "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    "Nothing will work unless you do.",
    "To be great is to be misunderstood.",
    "Success is not the absence of failure; it’s the persistence through failure.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "The only place where success comes before work is in the dictionary.",
    "You don’t have to be perfect to be amazing.",
    "The mind is everything. What you think you become.",
    "Go confidently in the direction of your dreams. Live the life you have imagined.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
    "The best way to predict your future is to create it."
]
